# Generated by Django 4.2 on 2024-03-07 15:54

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.AddField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date when car was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='udpated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date when car was modified'),
        ),
        migrations.AddField(
            model_name='car',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d8129d13-e2ca-42c3-a979-5990a65f88fb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Autos', 'Autos'), ('Pickups y Comerciales', 'Pickaups Y Comerciales'), ('SUVs y Crossovers', 'Suvs Y Crossovers')], help_text='Car type', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(help_text='Car extended description', max_length=500),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(help_text='Car image', upload_to='cars'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(help_text='Car model name', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(help_text='Car price in ARS'),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(help_text='Car brief description', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(help_text='Car year of production'),
        ),
    ]
