# Generated by Django 4.2 on 2024-03-07 18:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_id_car_created_at_car_udpated_at_car_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Feature image', upload_to='features')),
                ('title', models.CharField(help_text='Feature title', max_length=100)),
                ('description', models.TextField(help_text='Feature description', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when feature was created')),
                ('udpated_at', models.DateTimeField(auto_now=True, help_text='Date when feature was modified')),
            ],
            options={
                'unique_together': {('title', 'description')},
            },
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(help_text='Car features', to='cars.feature'),
        ),
    ]
