# Generated by Django 4.2 on 2024-03-08 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_uuid_feature_car_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(help_text='Dealership address', max_length=250, unique=True)),
                ('province', models.CharField(choices=[('Buenos Aires', 'Buenos Aires'), ('Catamarca', 'Catamarca'), ('Chaco', 'Chaco'), ('Chubut', 'Chubut'), ('Cordoba', 'Cordoba'), ('Corrientes', 'Corrientes'), ('Entre Rios', 'Entre Rios'), ('Formosa', 'Formosa'), ('Jujuy', 'Jujuy'), ('La Pampa', 'La Pampa'), ('Mendoza', 'Mendoza'), ('Misiones', 'Misiones'), ('Neuquen', 'Neuquenn'), ('Rio Negro', 'Rio Negro'), ('Salta', 'Salta'), ('San Juan', 'San Juan'), ('San Luis', 'San Luis'), ('Santa Cruz', 'Santa Cruz'), ('Santa Fe', 'Santa Fe'), ('Santiago del Estero', 'Santiago Del Estero'), ('Tierra del Fuego', 'Tierra Del Fuego'), ('Tucuman', 'Tucuman')], help_text='Dealership province', max_length=100)),
                ('phone', models.IntegerField(help_text='Dealership phone number')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when dealership was created')),
                ('udpated_at', models.DateTimeField(auto_now=True, help_text='Date when dealership was modified')),
            ],
        ),
    ]
