# Generated by Django 4.2 on 2024-03-08 12:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_dealership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Qualification of the car')),
                ('comment', models.CharField(help_text='Review comment', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when dealership was created')),
                ('udpated_at', models.DateTimeField(auto_now=True, help_text='Date when dealership was modified')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
    ]
