# Generated by Django 4.2 on 2024-03-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(blank=True, help_text='Car features', null=True, to='cars.feature'),
        ),
    ]
