# Generated by Django 4.2 on 2024-03-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealership',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when object was created'),
        ),
        migrations.AlterField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(blank=True, help_text='Car features', to='cars.feature'),
        ),
        migrations.AlterField(
            model_name='car',
            name='udpated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date when object was modified'),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when object was created'),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='udpated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date when object was modified'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when object was created'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='udpated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date when object was modified'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when object was created'),
        ),
        migrations.AlterField(
            model_name='review',
            name='udpated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date when object was modified'),
        ),
    ]
